sudo: required
services:
  - docker

before_install:
  - docker build -t beaglefoot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true beaglefoot/react-test npm test

after_success:
  - docker build -t beaglefoot/multi-client ./client
  - docker build -t beaglefoot/multi-nginx ./nginx
  - docker build -t beaglefoot/multi-server ./server
  - docker build -t beaglefoot/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push beaglefoot/multi-client
  - docker push beaglefoot/multi-nginx
  - docker push beaglefoot/multi-server
  - docker push beaglefoot/multi-worker
